= Channels
:page-aliases: data-routing.adoc, learn/sync-gateway-channels.adoc, sync-gateway-channels.adoc
:idprefix:
:idseparator: -
:url-httpie: https://github.com/jakubroztocil/httpie
:description: How to implement access-control and document routing using channels
:keywords: access control, document routing, sync,

include::partial$_std-hdr-sgw.adoc[]

:topic-group: Concepts
:param-abstract: Sync Gateway's Channels are a key part of a flexible approach to data routing and access control.
include::partial$block-abstract.adoc[]


== Introduction
Sync Gateway uses channels to make it easy to share a database's documents across a large user base whilst retaining effective access control.
They serve as a security conduit between the document and a user:

* Every document in the database is assigned a list of channels it belongs to.
* Every user is assigned a list of channels they are allowed to access.

This dual-purpose is reflected in the way you define channels:

* By assigning a channel to a user you are imposing access control
* By assigning a channel to a document you are imposing document routing


== Use-cases

You typically will use channels to:

* Control who can access what
* Partition your data set
* Enable users to access just the documents they need
* Minimize the amount of data synced to mobile devices


== Channel Wildcards

Sync Gateway provides two special channels, which are referred to using one of the *channel wildcards*.
These wildcards confer distinctly different access rights:

* <<lbl-public-channel>> wildcard ("!") -- essentially marks the document as publicly available; this provides for the public dissemination of documents. +
All users have access to all documents belonging to the Public Channel.
This access extends to users assigned no specific channel access.

* <<lbl-all-docs>> wildcard ("*") -- is essentially an Access All Areas pass. +
When assigned to a user it grants them access to a channel comprising all documents (including those from private channels).
Because of the wide-ranging access and the potential for syncing large volumes of data (sync pulls all documents in the bucket, regardless of channel), you are advised to only use this wildcard in conjunction with a filter.

This Sync Function -- see: <<ex-using-wildcard-channels>> -- shows how you might uses these wildcards

[#ex-using-wildcard-channels]
.Using wildcard channels
====
This example uses the _public channel_ and _all-documents channel_ wildcards for:

* Document Routing -- it routes public documents to the public channel
* Access Control  -- it grants all-documents access to an admin user.

[source, javascript]
----
// "sync": `
function sync(doc, oldDoc) {

  /* Validation -- add validation rules here */
  // e.g. Verify the requesting user is the oldDoc's user
  if ((oldDoc != null) && (oldDoc.username)) {
   	requireUser(oldDoc.username);
  }

  /* Routing -- add channel routing rules here */
  // e.g. add public docs to the public channel.
  if (doc.isPublic) {
    channel('!');
  } else {
    channel("channel." + getUserName()); // <.>
  }

  /* Access Control -- add user access rules here */
  // If this is an admin user, give access to all-docs channel
  if (doc.type == 'user') {
    requireRole('admin');
    access(doc.username, '*'); // <.>
  }

  //  further processing as required

  /* Supporting Functions */
  function getUserName() {
    return (isDelete() ? oldDoc.username : doc.username);
  }
}
// `

----

<.> If the document is public, we assign it to the _public channel_, otherwise we assign it to the user's channel

<.> For documents of type `user`, if the user has an admin role, we grant them access to the _all-documents channel_

====


[#lbl-public-channel]
== The Public Channel

The *Public Channel* , referred to by the wildcard symbol (`+!+`), is automatically created when Sync Gateway starts.

Documents added to this channel are visible to any user, even those assigned no channel access. +
New users are automatically granted access to the channel.
It is ideal for use in making information available across the user community.

For an example of how to use the public channel -- see: <<ex-using-wildcard-channels>>


[#lbl-all-docs]
== The All-Documents Channel

Assigning the *All-Documents Channel* wildcard, (`+*+`) to a user grants the user access to the *All-Documents* channel footnote:[This channel is sometimes referred to as the star channel.]

Note that this doesn't mean that the user is granted access to all available channels.
They are granted access to one channel, the *all documents* channel and all its documents.
This distinction is important when using the xref:sync-function.adoc#requireaccess-channels[`requireAccess()`] method -- see {sync-function--bmk-requireAcces}.

The *all documents* channel is automatically created and maintained by Sync Gateway.
It is a single channel to which all documents are automatically assigned, no matter what other channels they may be assigned-to, even private channels.

Assigning a channel to a user will not only allow them access to documents in the channel, it will also cause sync to pull all documents in that channel.

TIP: When using the _all-documents_ channel you will need to use a filter to avoid large numbers of documents being unnecessarily sync'd to mobile devices.

// You should also not explicitly assign a document to channel('*').
// It will result in unexpected behavior such as receiving the document twice on the client side.

You can assign channels using the sync function -- see xref:{sgw-pg-read-access}#add-access[Add Access].

For an example of how to use the all-documents channel -- see: <<ex-using-wildcard-channels>>


== Inspect a Document

You can use the admin REST API to see the channels that documents are assigned to.
Issue a {rest-api-admin--pfx}#/database/get
\__db___all_docs[/+\{db}+/_all_docs] request, and add the query parameter `?channels=true` to the URL -- see output response in <<ex-inspect-doc-response>>.


[#ex-inspect-doc-response]
.Output from Inspect Document
====
[source,json]
----
{
  "rows": [
    {
      "id": "foo",
      "key": "foo",
      "value": {
        "channels": [ // <.>
          "short",
          "word"
        ],
        "rev": "1-86effb929acbf953905dd0e3974f6051"
      }
    }
  ],
  "total_rows": 16,
  "update_seq": 26
}
----
<.> The output shows that the document is in two channels: `short` and `word`.
====


== Add to Channel

You assign documents to channels in a Sync Function.
You can provide this function in the configuration file ({configuration-properties--pfx}#databases-this_db-sync[databases.$db.sync]).
The Sync Function is a JavaScript function that takes a document body as input and, based on the document content, decides what channels to assign the document to (see the xref:sync-function.adoc#function-definition[Function Definition]).

Based on the contents of the document, the Sync Function can call xref:sync-function.adoc#channelchannelname[channel()] to add the document to one or more channels -- see <<ex-use-channel>>
This makes it accessible to users who have access to those channels, and will cause the document to be pulled by users that are subscribed to those channels.


[#ex-use-channel]
.Routing Documents
====
[source,javascript]
----
function (doc, oldDoc) {
  channel("foo"); // <.>
}
----
<.> The Sync Function routes incoming documents to a channel named `foo`.
====

Channels are created as documents are assigned to them.
The Sync Function cannot reference any external state and must return the same results every time it's called on the same input.

Valid channel names consist of text letters `[A–Z, a–z]`, digits `[0–9]`, and a few special characters `[= + / . , _ @]`.
Channel names are case-sensitive.
Channels with no documents assigned to them are empty.

If you don't supply a Sync Function in the configuration file, Sync Gateway uses the {configuration-properties--pfx}#databases-this_db-sync[default Sync Function].
This default function is really only useful for experimentation and development.

TIP: You are advised to write a Sync Function that provides validation, routing and access-control appropriate to your business needs -- see: {sync-function--xref} for more on sync functions.


== Remove from Channel

If the document was previously routed to a channel, but the current call to the sync function (for an updated revision) doesn't route it to that channel, the document is removed from the channel.

This may cause users to lose access to that document.
If that happens, the next time Couchbase Lite pulls changes from the gateway, it will purge the document from the database and trigger the document replication listener on Couchbase Lite with the `AccessRemoved` flag.

:param-page: replication
:param-bookmark: replication-events
include::partial$blocklinks-cbl.adoc[]


== Limits and Constraints

=== Channel Limits

.Guidance on Channel Assignment Limits
[#tbl-limits, cols="2,4,^3", options="header"]
!===

| Element
| Limiting factor
| Guidance Limit (Channels)

| Channels per document
| The amount of memory consumed by the combined number of channels and access grants must fit within the maximum 1Mb xattr size limit -- see: <<tbl-metadata-size>>.
| 50

| Channels per user
a| The amount of memory consumed by channels must fit within the 20 MB available on Couchbase Server docs for storing metadata -- see: <<tbl-metadata-size>> +
Note that the memory is retained for as long as the replication remains active.
| 1,000

!===


=== Sync Metadata Limits

Every time a document is assigned to a new channel, the channel name is appended to that document's sync metadata.

Therefore, a document's set of channels is limited by the allowed sync metadata size described in <<tbl-metadata-size>>.

.Size Limits for Sync Metadata
[#tbl-metadata-size,cols="^4,^4", options="header"]
|===

|Value of `enable_shared_bucket_access`
|Size (Mb per Document)

m|false
|20

m|true
|1

|===

Sync Gateway will assign a document to a new channel as long as the sync metadata remains under the allowed limit.

*What to do when your channel count exceeds the usable space for sync metadata?*

In order to lower the sync metadata size per document, you can do one of the following:

* Lower the number of channels per document.
* Shorten the channel names.
A shorter channel name will occupy less space ("customer==0030169303" vs "cs==0030169303").
* Lower the {configuration-properties--pfx}#databases-this_db-revs_limit[revs_limit] value.
Indeed, a copy of channel metadata is retained for each revision of a document.


include::partial$block-related-content-sync.adoc[]