= Conflict Resolution in Inter-cluster Replication
// = Inter-Cluster Replication
:page-layout: article
:page-status: {release-status-sgw} -- {release-comments-sgw}
:page-edition: Under Development
:page-role:
:description: This content covers conflict resolution and inter-cluster replication (replication between Sync Gateway clusters using SG-Replicate 2.0)
:keywords:

include::partial$_std-hdr-sgw.adoc[]

:topic-group: Inter-cluster Replication
:param-related: {xref-sgw-pg-config-properties} | {xref-sgw-pg-rest-api-admin}
:param-abstract: Inter-cluster replication conflict resolution policies and behaviors.
include::partial$block-abstract.adoc[]

ifeval::["{releaseStatus}" == "gamma"]
[.pane__frame--orange]
.Author's Notes
--
Information sources include:

* https://issues.couchbase.com/browse/DOC-6465
* https://docs.google.com/document/d/13E6JOq8u_AaUd_t8FZEPCAuq7jfkjryecjBQBHE3pG8/edit?ts=5e7cd22f#heading=h.ho0j9x72yi1l
--
endif::[]

Useful resources: https://blog.couchbase.com/document-conflicts-couchbase-mobile/[blog-- Document Conflicts and Automatic Conflict Resolution] | https://blog.couchbase.com/conflict-resolution-couchbase-mobile/[blog-- Demystifying Conflict Resolution] | https://blog.couchbase.com/tag/conflict-resolution/[Blog category -- Conflict Resolution] |{xref-sgw-pg-resolving-conflicts}

== Overview
// tag::overview[]
SG-Replicate 2.0 replication supports automatic conflict resolution to resolve conflicting document changes (revisions).
Out-of-the-box, the conflict resolution policy echoes that applied in replications between Couchbase Lite and Sync Gateway.

//  even when the no-conflicts mode is enabled (that is where xref:config-properties.adoc#databases-foo_db-allow_conflicts["allow_conflicts": false]).

// When running two Sync Gateway clusters with the no-conflicts mode enabled, cross-cluster document conflicts will result in that document no longer being replicated. To avoid this, the application must ensure that concurrent cross-cluster updates are not made to a given document.

// Deployments  must implement a custom conflict resolver in an external app as specified in {xref-sgw-pg-resolving-conflicts}.
// // end::overview[]


NOTE: {community} and SG-Replicate 1.0 replications do not support conflict resolution. You should set `allow_conflict=true` on both the `source` and `target`.

Conflict resolutions applies only in {enterprise} licensed deployments.

== Resolver Policies
SG-Replicate 2.0 supports out-of-the-box (predefined ) conflict resolver policies.
The following policies are available as Javascript functions, which can be used when configuring a replication:

* `UseDefault` -- This uses the automatic resolution policy (last-write-wins) as defined  above)
* `LocalWins` Local Wins
* `RemoteWins` Remote Wins

== Conflict Resolution Approaches

=== Automatic Conflict Resolution
SG-Replicate 2.0 supports automatic conflict resolution to resolve conflicting document revisions.

The automatic conflict resolution policy is the same as that adopted in Couchbase Lite 2.x between Couchbase Lite and Sync Gateway.
The basic rules being:

include::couchbase-lite:ROOT:partial$handling-conflicts.adoc[tags=auto-conflict-resolution]

=== Custom Conflict Resolution

Custom conflict resolution is handled by conflict resolvers (see: <<resolver-policies>>), Javascript functions embedded in the configuration.

Pull Replications::
+
--
For _Pull_ replications the _active_ Sync Gateway is responsible for detecting and resolving conflicts based on the configured conflict resolver function ({xref-sgw-pg-config-properties-db-rep-resolver}).

This is also how conflicts are handled when Couchbase Lite clients pull down documents to Sync Gateway.

There are two ways to handle conflicts in your custom_conflict_resolver, you can either:

* Choose a _winning_ revision from among the conflicting revisions (see simple-conflict-resolver), or
* Merge two or more conflicting revision to create a new _winning_ revision; losing revisions are tomb-stoned.


*Note:* Resolved conflicts are only transferred from active to passive Sync Gateways if a replication is setup between them.

--

Push Replications::
For _Push_ replications, the _passive_ Sync Gateway automatically detects and rejects conflicting changes being pushed to it.
+
Note that conflicts are not resolved.
The revision is rejected and the document returned -- with a `409 Conflict` -- response to the active Sync Gateway.
+
This approach is the same as that adopted when Couchbase Lite clients push documents to Sync Gateway.


[.simple-conflict-resolver]
.Simple conflict resolver
=====
[source, json]
----
"replication": [
  {
  "replication_id": "replication1",
  // other config as required
  "conflict_resolver": `
    function(local, remote) {
      if (doc.type == "a-doctype-1") {
          Return RemoteWins(doc,oldDoc);
        }
        else {
        Return UseDefault(doc,oldDoc);
        }
    }
    `
// other config as required
  }
]
----
=====


include::partial$block-related-content-icr.adoc[]