= ICR Administration and Management
:page-layout: article
:page-status: {release-status-sgw} -- {release-comments-sgw}
:page-edition: Under Development
:page-role: panes
:description: This content covers the administration and management of inter-cluster replications
:keywords:

include::partial$_std-hdr-sgw.adoc[]
// include::partial$block-authors-notes.adoc[tag=wip]
:topic-group: Inter-cluster Replication
:param-related: {xref-sgw-pg-config-properties} | {xref-sgw-pg-rest-api-admin}
:param-abstract: Inter-cluster replication conflict resolution policies and behaviors.
include::partial$block-abstract.adoc[]

ifeval::["{release-status-sgw}" == "gamma"]
[.pane__frame--orange]
.Author's Notes
--
Document relevant aspects of _replication administration_.

Information sources include:

*  https://issues.couchbase.com/browse/DOC-6493
* https://docs.google.com/document/d/13E6JOq8u_AaUd_t8FZEPCAuq7jfkjryecjBQBHE3pG8/edit?ts=5e7cd22f#heading=h.b2gu37hg0ou0
* See: https://docs.google.com/document/d/13E6JOq8u_AaUd_t8FZEPCAuq7jfkjryecjBQBHE3pG8/edit?ts=5e7cd22f#heading=h.b2gu37hg0ou0 for content
--
endif::[]


== Admin capabilities

// tag::overview[]
// end::overview[]

The Admin REST API provides a number of endpoints to assist in the monitoring, administration and management of replications.

You can use these to conduct Sync Gateway cluster administration, whether manually or by using automation (for example, scripts or a container orchestration system such as  Kubernetes).

// Manual operation will typically take place where a cluster is malfunctioning and needs troubleshooting, or in demonstration and development environments.
// For instance, in the process of debugging why a replication is slow, there would be a need to temporarily stop a replication and subsequently restart when the issue is resolved.  Another case would be if the parameters of the replication need to change.

The Admin Rest API provides two endpoints with admin capabilities:

_replication::
* List - get
* Update - put
* Remove - del

_replicationStatus::
* Stop
* Start
* Reset


//

== Listing Replications
// Use of `_active_tasks` is deprecated.

You can get a list of all replications across all nodes by using the `_replicate GET` endpoint.

The list includes replications initiated using configuration or REST APi and can be in any state.

.Listing replications
=====
[{tabs}]
====
Request::
+
--
[source, json]
----
include::example$configuration/sync-gateway-config.json[tag=icr-rep-list-replications-req]
----
--

Body::
+
--
[source, json]
----
include::example$configuration/sync-gateway-config.json[tag=icr-rep-list-replications-body]
----
--

Response::
+
--
[source, json]
----
include::example$configuration/sync-gateway-config.json[tag=icr-rep-list-replications-resp]
----
--
====
=====

== Getting Replication Details

.Get a replication's definitions
=====
[{tabs}]
====
Request::
+
--
[source, json]
----
include::example$configuration/sync-gateway-config.json[tag=icr-rep-retrieve-replications-req]
----
--

Response::
+
--
[source, json]
----
include::example$configuration/sync-gateway-config.json[tag=icr-rep-retrieve-replications-resp]
----
--
====
=====

The following example retrieves definitions for all replications on a specified database, regardless of the node on which it was configured.
The results are returned in an array; one entry per replication.


.Get all replication details for a database
=====
[{tabs}]
====
Request::
+
--
[source, json]
----
include::example$configuration/sync-gateway-config.json[tag=icr-rep-retrieve-replications-req-all-for-db]
----
--

Response::
+
--
[source, json]
----
include::example$configuration/sync-gateway-config.json[tag=icr-rep-retrieve-replications-resp-all-for-db]
----
--
====
=====

== Updating a Replication

.Update a replication's details
=====
[{tabs}]
====
Request::
+
--
[source, json]
----
include::example$configuration/sync-gateway-config.json[tag=icr-rep-update-replications-req]
----
--
+
// Body::
// +
// --
// [source, json]
// ----
// include::example$configuration/sync-gateway-config.json[tag=icr-rep-update-replications-body]
// ----
// --
Response::
+
--
A successful update will return a 200 response, with the following body:
[source, json]
----
include::example$configuration/sync-gateway-config.json[tag=icr-rep-update-replications-resp]
----
--
====
=====

See: {xref-sgw-pg-admin-rest-api}  |  Endpoint {xref-sgw-endpoint-admin-api-replication-put}

== Removing a Replication

Deleting a replication will remove:

* The persisted replication definition
* All checkpoints associated with the replication
* All replication status information associated with the replication

.Removing a replication
=====
[{tabs}]
====

Request::
+
--
[source, json]
----
include::example$configuration/sync-gateway-config.json[tag=icr-rep-remove-replications-req]
----
--

Response::
+
--
[source, json]
----
include::example$configuration/sync-gateway-config.json[tag=icr-rep-remove-replications-resp]
----

--
====
=====

See: {xref-sgw-pg-admin-rest-api}  |  Endpoint {xref-sgw-endpoint-admin-api-replication-delete}

== Canceling a Replication

An active replication task is canceled by sending a PUT or POST request to the server endpoint `_replication`, with a JSON object.

The JSON object's body must contain the parameter `"cancel": true` and a valid `replication_id`.

Note that the details within the body of the request must be identical to the original replication for the cancelation request to be honoured.

So if. for example, the original request was a one-shot replication you can omit the `"continous": false` parameter; false is the default value and so will match the original details.

.Canceling a replication
=====

[{tabs}]
====
Using replication_id::
+
--
This example will cancel an active replication with a `replication_id` of "my-one-shot-replication", the `replication_id` value can be obtained by sending a request to `_active_tasks`.

[source,javascript]
----
include::example$configuration/sync-gateway-config.json[tag=icr-rep-cancel-replications-body]
----
--

Without replication_id::
+
--
This will cancel a replication that was started with same "source" and "target" values as those in the cancel request.
By omitting the "continuous" property it's value will default to *false*, a replication must also have been started as a one-shot to match.

[source,javascript]
----
include::example$configuration/sync-gateway-config.json[tag=icr-rep-cancel-replications-body-no-id]
----
--

Response::
+
--
When an active task is canceled, the response returns the stats of the replication up to the point when it was stopped.

[source,javascript]
----
include::example$configuration/sync-gateway-config.json[tag=icr-rep-cancel-replications-resp]
----
--
====
=====




== Getting Replication Status Data

.Get status data for a specified replication
=====
[{tabs}]
====
Request::
+
--
[source, json]
----
include::example$configuration/sync-gateway-config.json[tag=icr-rep-retrieve-replication-status-req]
----
--

Response::
+
--
[source, json]
----
include::example$configuration/sync-gateway-config.json[tag=icr-rep-retrieve-replication-status-resp]
----
--
====
=====

The following example retrieves status data for all replications that meet the specified criteria.

The results are returned in an array; one entry per replication.

.Get status data for all replications meeting criteria
=====
[{tabs}]
====
Request::
+
--
This example's criteria selects non-active, local, adhoc or persistent Rest API replications.

[source, json]
----
include::example$configuration/sync-gateway-config.json[tag=icr-rep-retrieve-replication-status-req-all]
----
--

Response::
+
--
[source, json]
----
include::example$configuration/sync-gateway-config.json[tag=icr-rep-retrieve-replication-status-resp-all]
----
--
====
=====

== Starting a Replication

Stop an active persistent or ad hoc replication

For example to offline an edge cluster without waiting for a long replication to complete. The convenience API means only the `replication_id` parameter is required.

.Start a replication
=====
[{tabs}]
====
Request::
+
--
[source, json]
----
include::example$configuration/sync-gateway-config.json[tag=icr-rep-start-replications-req]
----
--

Response::
+
--
[source, json]
----
include::example$configuration/sync-gateway-config.json[tag=icr-rep-start-replications-resp]
----
--

====
=====

== Stopping a Replication

Stop an active persistent or ad hoc replication

For example to offline an edge cluster without waiting for a long replication to complete. The convenience API means only the `replication_id` parameter is required.

.Stopping replications
=====
[{tabs}]
====
Request::
+
--
[source, json]
----
include::example$configuration/sync-gateway-config.json[tag=icr-rep-stop-replications-req]
----
--

Response::
+
--
[source, json]
----
include::example$configuration/sync-gateway-config.json[tag=icr-rep-stop-replications-resp]
----
--

====
=====

== Resetting a Replication

Reset a persistent replication

This is useful to escape a system state where one or more documents have failed to sync but where resuming from previous synced checkpoint would skip over those documents.

.Reset a replication
=====
[{tabs}]
====
Request::
+
--
[source, json]
----
include::example$configuration/sync-gateway-config.json[tag=icr-rep-reset-replications-req]
----
--

Response::
+
--
[source, json]
----
include::example$configuration/sync-gateway-config.json[tag=icr-rep-reset-replications-resp]
----
--
====
=====

include::partial$block-related-content-icr.adoc[]


// == Updating a Replication

// .Update a replication's details
// =====
// [{tabs}]
// ====
// Request::
// +
// --
// include::example$configuration/sync-gateway-config.json[tag=icr-rep-list-replications-req]
// --

// Body::
// +
// --
// include::example$configuration/sync-gateway-config.json[tag=icr-rep-list-replications-body]
// --

// Response::
// +
// --
// include::example$configuration/sync-gateway-config.json[tag=icr-rep-list-replications-resp]
// --

// ====
// =====

