// BEGIN how-to -- HOW-TO ALLOW ACCESS
// Parameters -- use-topic-header -- to show the topic heading (optional)
[,cols="1,4", grid="none", frame="none"]
|===
|_Related Concepts_:
a|{access--xref} \| {access-control-model--xref} \| {channels--xref}
// include::{concepts}access-control-model.adoc[tag=summary]
|===


== Read Access Control

Channels form the core of the Sync Gateway Access Control model.

Every document in the database is assigned a list of channels it is distributed to.
Every user (or role) is granted access to a list of channels.

Channels can be user-defined or they can be system channels (like the public, all-docs, wildcard)

This dual-purpose is reflected in the way you use channels:

* By granting a user (or role) access to a channel, you are imposing access control. Users can only access documents that are channels that they have been granted access to.

* By assigning a document to a channel you are imposing document routing and data segregation

You grant roles and-or users access to channels using:

* Admin Rest API +
 Using admin_channels property using the admin REST API endpoint -- see {rest-api-admin-user-put--xref}
* Dynamically via Sync Function  +
 Programmatically within the sync function using the exposed helper function access() — see {sync-function-api--xref}
* Configuration File (pre 3.0) +
Using the appropriate `admin_channels` property in the {configuration-schema-static--xref}. +
*Note:* This option is disabled by default in 3.0. To use it in 3.0, you must set the `disable_persistent_config` flag to `true`


== Process

.Allow Access
[{tabs}]
====

Admin REST API::
+
--
Add a channel to an existing user by sending a PUT request to the Admin Rest API `_role` endpoint ({rest-api-admin-role-put--xref} ).

Specify the roles to be assigned in the `admin_channels` array.

[source,bash]
----
$ curl -vX PUT "http://localhost:4985/mydatabase/_user/{user}" -H //<.>
"accept: application/json" -H "Content-Type: application/json" -d
'{ "admin_channels": ["Channel1","Channel3]}' // <.>
----

<.> {user} is the user name to be updated, e.g. "Edge1User"

<.> Here we add _Channel1_ and _Channel3_ to the user

--

+
Sync Function::
+
--

You can also use the Sync Function's {sync-function-api-access-cmd--xref} function to allow channel access to roles and-or users programmatically.

In the case where channel assignment is done dynamically via the sync function, the channel(s) to which user/role is assigned is identified in two ways

Document contents::
+
The role can be derived or specified as a property within the document body. In this case, the document content itself is used to govern access and routing
+

[source, javascript]
----

function (doc, olddoc) {

  // user logic
    access ("Edge1User", "RandomChannel"); // <.>
    access ("role:Edge2", "SkyChannel"); // <.>

  // user logic
}
----
+
<.> Here we add access to channel _RandomChannel_ to the user _Edge1User_
+
<.> The `access()` function can also operate on roles.
If a user name string begins with `role:` then the remainder of the string is interpreted as a role name.
There's no ambiguity here, because ":" is an illegal character in a user or role name.
Here we allow access to the channel _Sky1Channel_  for the role _Edge2_

User Defined XATTR (3.0+)::
+
Starting 3.0, the role can be specified within a special user-defined xattr associated with the document -- see: {using-xattr-access-grants--xref}.
+

[source, javascript]
----
include::{examples-code-js}[tags="sync-function-using-xattr"]
----
+

include::{examples-code-js}[tags="sync-function-using-xattr-notation"]

--

Configuration::
+
--
Add a channel to a user in the configuration file.
This method is convenient for testing and to get started.
Use the *Admin REST API* for production systems.

[source,json]
----
{
  "databases": {
    "mydatabase": {
      "users": {
        "GUEST": {"disabled": true},
        "Edge1User": {"password": "pass", "admin_roles": ["Edge1"],
              "admin_channels": ["Channel1","Channel3","RandomChannel"]} // <.>
      },
      "roles": {
        "Edge1": {"admin_channels": ["channel1", "channel3"]},
        "Edge2": {"admin_channels": ["Channel2","Channel3","SkyChannel"]} // <.>
      }
    }
  }
}
----

<.> Here we have added the channel _RandomChannel_ to the user _Edge1User_ {configuration-schema-static--pfx}#databases-this_db-users-this_user-admin_channels[databases.$db.users.$user.admin_channel]

<.> Here we have added the channel _SkyChannel_ to the role _Edge2_ {configuration-schema-static--pfx}#databases-this_db-roles-this_role-admin_channels[databases.$db.users.$user.admin_channel]

--


====

// END how-to -- ALLOW ACCESS
