// BEGIN how-to -- HOW-TO CREATE A USER
// Parameters -- use-topic-header -- to show the topic heading (optional)

ifdef::include-related[]
Related Concepts::
+
--
{users--xref}
include::{concepts}users.adoc[tag=summary]
--
endif::[]


== Provisioning

You can create and-or manage users by:

* Using Sync Gateway's Admin REST API -- {rest-api-admin--xref}.
*  Configuring OIDC to auto-register a user following successful validation of an ID Token -- {authentication-users--xref}.
* Pre 3.x users, or 3.x users running with `disable_persistent_config=true`, can use the Configuration File to add users -- see  {configuration-schema-static--xref}

[{tabs}]
====

Admin Rest API::
+
--
Create a new user by sending a POST request to the Admin Rest Api `_user` endpoint ({rest-api-admin-user-post--xref}).
Update existing users by sending a PUT instead; in this case include the user name at the end of the url.

The user credentials (**username**/**password**) are passed in the request body.

[source,bash]
----
$ curl -vX POST "http://localhost:4985/mydatabase/_user/" -H
"accept: application/json" -H "Content-Type: application/json" -d
'{"name": "Edge1User", "password": "pass"}' // <.>

$ curl -vX PUT "http://localhost:4985/mydatabase/_user/Edge1User" -H
"accept: application/json" -H "Content-Type: application/json" -d
'{"name": "Edge1User", "admin_channels": ["RandomChannel"]}' // <.>
----

<.> Add new user "Edge1User", no `access_channel` or `role` is specified here.
<.> Update existing user "Edge1User" and add `access_channels` data

--

OIDC::
+
--

include::{examples-lib}[tags="oidc-rest-api-simple"]

<.> Use `register=true` to automatically create a Sync Gateway user on successful completion of vaidation.

--

Configuration File::
+
--
Pre 3.x users, or 3.x users running with `disable_persistent_config=true` ONLY.

[source,json]
----
{
  "databases": {
    "mydatabase": {
      "users": { // <1>
        "GUEST": {"disabled": true},
        "Edge1User": {"password": "pass",
                      "admin_channels": ["RandomChannel"]},
      }
    }
  }
}
----

<.> {configuration-schema-static--pfx}#databases-this_db-users[databases.$db.users]

<.> Here we add the Edge1 role used in the example in this topic.

--


====

// END how-to -- HOW-TO CREATE A USER